name: Secrets scanner

on:
  pull_request:

jobs:
  secrets-scanner:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trufflehog branch scan
        id: trufflehog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --debug --only-verified
        continue-on-error: true

      - name: Scan results status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
